### ISSUE TITLE
..getProjectMetadata does not exist

### ISSUE THREAD

**Issue by ghost** [Bviveksingh/angular-frontend#2]
Running ng serve
I obtain the following error message:
Job name "..getProjectMetadata" does not exist.
Error: Job name "..getProjectMetadata" does not exist.

Any suggestions how to resolve this?

**Comment by Bviveksingh** [comment]
Have you upgraded or downgraded the version of angular ?

**Comment by ghost** [comment]
I used npm install to install the dependencies, however the angular version I am using is:

Angular CLI: 8.0.6
Node: 12.16.1
OS: win32 x64
Angular: 8.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.6
@angular-devkit/build-angular     0.901.7
@angular-devkit/build-optimizer   0.901.7
@angular-devkit/build-webpack     0.901.7
@angular-devkit/core              8.0.6
@angular-devkit/schematics        8.0.6
@angular/cdk                      8.2.3
@angular/cli                      8.0.6
@angular/material                 8.2.3
@ngtools/webpack                  9.1.7
@schematics/angular               8.0.6
@schematics/update                0.800.6
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.42.0

**Comment by Bviveksingh** [comment]
Sorry for the late reply. 

Check this link:
[https://stackoverflow.com/questions/60174503/job-name-getprojectmetadata-does-not-exist](url)

**Comment by ghost** [comment]
Thanks for the reply :)
I got it to compile with downgrading as described in the Stackoverflow post.
Unfortunately, when opening the localhost:4200 link given in Chrome I see just an empty page named FrontEnd and with the Angular Icon as thumbnail. 
Other Angular apps work just fine, do you have a suggestion for me?

**Comment by Bviveksingh** [comment]
Do you see in any errors in the console or terminal? If yes, can you send a screenshot of the errors.

**Comment by ghost** [comment]
No there are no errors on the console when running ng serve.
However, running ng test some unit tests fail, see error log attached.
[Karma_error_log.pdf](https://github.com/Bviveksingh/angular-frontend/files/4809759/Karma_error_log.pdf)

**Comment by Bviveksingh** [comment]
Can you upload your code to a GitHub repository and send the url? I'll check it out.

**Comment by ghost** [comment]
I uploaded the code to https://github.com/hcl734/blog_proj
Thanks for the help!

**Comment by Bviveksingh** [comment]
Hey, I got it working. I understood what was going wrong. Can you mail me at **bviveksingh96@gmail.com** so that I explain you in detail what's going wrong with the application.

**Comment by Bviveksingh** [comment]
I'm closing the issue since I have explained the process of solving the issue.
